[build]
  command = "ng build --configuration production"
  publish = "tintoexpres/dist/tintoexpres/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200